#!/usr/bin/env python3
import sys
import zlib

bank_size = 16 * 1024  # FIXED SIZE FOR THE SEGA MASTER SYSTEM AND GAME GEAR PLATFORMs
bank_count = 16  # Set to 16 for a 256 KB ROM
rom_crc = 0xB519E833


def main() -> None:
    rom_fname, annot_fname, whole_fname = sys.argv[1:]

    rom_data = open(rom_fname, "rb").read()
    assert len(rom_data) == bank_count * bank_size
    assert (zlib.crc32(rom_data) & 0xFFFFFFFF) == rom_crc
    rom = Rom(data=rom_data)

    rom.save(file_name=whole_fname)


class Rom:
    def __init__(self, *, data: bytes) -> None:
        self.data = data

    def save(self, *, file_name: str) -> None:
        with open(file_name, "w") as outfp:
            outfp.write(f";; Autogenerated with the following command:\n")
            outfp.write(f";;    python3 {' '.join(map(repr, sys.argv[:]))}\n")
            outfp.write(f";; Do NOT hand-edit!\n")

            # Write memory map
            outfp.write(f"\n.MEMORYMAP\n")
            outfp.write(f"SLOT 0 START $0000 SIZE $4000\n")
            outfp.write(f"SLOT 1 START $4000 SIZE $4000\n")
            outfp.write(f"SLOT 2 START $8000 SIZE $4000\n")
            outfp.write(f"SLOT 3 START $C000 SIZE $2000\n")
            outfp.write(f"DEFAULTSLOT 2\n")
            outfp.write(f".ENDME\n")

            # Write ROMBANKMAP
            outfp.write(f"\n.ROMBANKMAP\n")
            outfp.write(f"BANKSTOTAL 16\n")
            outfp.write(f"BANKSIZE $4000\n")
            outfp.write(f"BANKS 16\n")
            outfp.write(f".ENDRO\n")

            # Write ROM
            for bank_idx in range(16):
                # Assume all banks past the first 2 want to be in slot 2
                slot_idx = min(2, bank_idx)
                outfp.write(
                    f'\n.SECTION "Bank{bank_idx:02d}" SLOT {slot_idx} BANK {bank_idx} FORCE ORG $0000\n'
                )
                bank = self.data[bank_idx * bank_size :][:bank_size]
                # Do a hexdump
                for row_idx in range(bank_size // 16):
                    row_addr = row_idx * 16
                    row = ", ".join(f"${v:02X}" for v in bank[row_idx * 16 :][:16])
                    outfp.write(
                        f".db {row}  ; {bank_idx:02d}:{(slot_idx*bank_size)+row_addr:04X}\n"
                    )
                outfp.write(f".ENDS\n")


if __name__ == "__main__":
    main()
